# Generated by Django 5.1.3 on 2024-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='diagram',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
