# Generated by Django 5.1.3 on 2024-11-25 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapplication', '0003_userdetail_dob_userdetail_is_computer_literate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(blank=True, default='2006-01-01', verbose_name='Date of birth'),
        ),
    ]
