# Generated by Django 5.1.3 on 2024-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapplication', '0004_userdetail_created_at_alter_userdetail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
    ]
